/**
 * Canonical Care Dent catalogue.
 * Content transcribed from the official "Catalog new.pdf" product brochure.
 * Images live in FRONTEND/public/products and are served by the web app.
 */

export const COMPANY = {
  name: 'Care Dent',
  tagline: 'We care for your precious equipments',
  founder: 'Mr. Sivakumar',
  experienceYears: '30+',
  established: 'January 2023',
  address: 'Roshan Villa, No.64, 2nd Street, Arumugam Nagar, Mugalivakkam, Chennai - 600 125',
  phoneNumbers: ['+91 94441 53599', '+91 98844 18360'],
  email: 'jashvish.siva@gmail.com',
  whatsappNumber: '919444153599',
  workingHours: 'Monday - Saturday: 9:00 AM - 7:00 PM',
};

const commonChairSpecs = [
  { label: 'Suction System', value: 'Motorised Dryco suction with silencer, auto-drain and auto-flush' },
  { label: 'Standard Attachments', value: '3-way syringe x2, Airotor points x2, Micromotor x1' },
  { label: 'Foot Control', value: 'Multi-functional foot control' },
  { label: 'Stool Included', value: 'Doctor operated dental stool' },
  { label: 'Instrument Tray', value: 'Stainless steel instrument tray' },
];

export const PRODUCTS = [
  /* ------------------------------ dental chairs ------------------------------ */
  {
    slug: 'gamma-overhanging',
    name: 'Gamma Overhanging',
    tagline: 'Uncompromised Legroom & Modern Minimalist Design',
    kind: 'chair',
    stock: 2,
    lowStockThreshold: 1,
    reorderQuantity: 2,
    category: 'Dental Chairs',
    series: 'Gamma Series',
    brand: 'Care Dent',
    badge: 'Flagship Ergonomics',
    isFeatured: true,
    sortOrder: 1,
    heroImage: '/products/gamma-overhanging.jpg',
    images: ['/products/gamma-overhanging.jpg'],
    description:
      'Our flagship over-the-patient delivery chair, built for operators who want maximum legroom and an uncluttered field of view. A six-programme memory system, integrated Woodpecker optic scaler and 39,000 lux LED light make it the most complete unit in the Gamma range.',
    keyDifferentiators: [
      'Electrically operated with 6 programmes and chair-mounted side attachments',
      '1 to 3 erasable programmes, plus Zero, Gargle and SH-Supine positions',
      'LED light with on/off control at 39,000 lux - 3 yellow and 3 white LEDs, adjustable brightness, lux and kelvin',
      'Rotating ceramic bowl spittoon fitted in a square box unit',
      'Modular trolley with over-hanging (over-the-patient) delivery system',
      'Motorised Dryco suction with silencer, auto-drain and auto-flush',
      'Memory foam upholstery',
      'Woodpecker OPTIC scaler unit with 5 scaling tips and control switch',
      'X-ray viewer and multi-functional foot control',
      'Doctor operated dental stool and SS instrument tray',
    ],
    specifications: [
      { label: 'Operation Type', value: 'Electrically operated, 6 programmes' },
      { label: 'Programmes', value: '1-3 erasable, Zero, Gargle, SH-Supine' },
      { label: 'Delivery System', value: 'Over-hanging (over-the-patient) modular trolley' },
      { label: 'Light', value: 'LED, 39,000 lux, 3 yellow + 3 white, adjustable lux & kelvin' },
      { label: 'Spittoon', value: 'Rotating ceramic bowl in square box unit' },
      { label: 'Scaler', value: 'Woodpecker OPTIC scaler, 5 tips, with control switch' },
      { label: 'Upholstery', value: 'Memory foam' },
      { label: 'X-Ray Viewer', value: 'Included' },
      ...commonChairSpecs,
    ],
  },
  {
    slug: 'gamma-premium',
    name: 'Gamma Premium',
    tagline: 'The Paradigm of Professional Reliability',
    kind: 'chair',
    stock: 2,
    lowStockThreshold: 1,
    reorderQuantity: 2,
    category: 'Dental Chairs',
    series: 'Gamma Series',
    brand: 'Care Dent',
    badge: 'Best Seller',
    isFeatured: true,
    sortOrder: 2,
    heroImage: '/products/gamma-premium.jpg',
    images: ['/products/gamma-premium.jpg'],
    description:
      'The workhorse of the Gamma range. Same six-programme electrics and 39,000 lux LED light as the Overhanging model, paired with an imported handpiece cavity holder and memory foam upholstery. OPG viewer available as an option.',
    keyDifferentiators: [
      'Electrically operated with 6 programmes and chair-mounted side attachments',
      '1 to 3 erasable programmes, plus Zero, Gargle and SH-Supine positions',
      'LED light with on/off control at 39,000 lux - 3 yellow and 3 white LEDs, adjustable brightness, lux and kelvin',
      'Rotating ceramic bowl spittoon fitted in a square box unit',
      'Memory foam upholstery with imported handpiece cavity holder',
      'Motorised Dryco suction with silencer, auto-drain and auto-flush',
      'Woodpecker Non-Optic scaler unit with 5 scaling tips and control switch',
      'X-ray viewer (OPG viewer optional) and multi-functional foot control',
      'Doctor operated dental stool and SS instrument tray',
    ],
    specifications: [
      { label: 'Operation Type', value: 'Electrically operated, 6 programmes' },
      { label: 'Programmes', value: '1-3 erasable, Zero, Gargle, SH-Supine' },
      { label: 'Light', value: 'LED, 39,000 lux, 3 yellow + 3 white, adjustable lux & kelvin' },
      { label: 'Spittoon', value: 'Rotating ceramic bowl in square box unit' },
      { label: 'Scaler', value: 'Woodpecker Non-Optic scaler, 5 tips, with control switch' },
      { label: 'Upholstery', value: 'Memory foam, imported handpiece cavity holder' },
      { label: 'X-Ray Viewer', value: 'Included (OPG viewer optional)' },
      ...commonChairSpecs,
    ],
  },
  {
    slug: 'gamma',
    name: 'Gamma',
    tagline: 'Precision for You. Peace of Mind for Them',
    kind: 'chair',
    stock: 2,
    lowStockThreshold: 1,
    reorderQuantity: 2,
    category: 'Dental Chairs',
    series: 'Gamma Series',
    brand: 'Care Dent',
    badge: 'Best Value',
    isFeatured: true,
    sortOrder: 3,
    heroImage: '/products/gamma.jpg',
    images: ['/products/gamma.jpg'],
    description:
      'Full six-programme Gamma electrics with a hanging-cord modular trolley and a choice of ceramic or thick glass bowl - the practical entry into the Gamma series without giving up the 39,000 lux LED light or the Woodpecker scaler.',
    keyDifferentiators: [
      'Electrically operated with 6 programmes and chair-mounted side attachments',
      '1 to 3 erasable programmes, plus Zero, Gargle and SH-Supine positions',
      'LED light with on/off control at 39,000 lux - 3 yellow and 3 white LEDs, adjustable brightness, lux and kelvin',
      'Choice of ceramic bowl or thick glass bowl',
      'Modular trolley fitted with hanging cord',
      'Imported handpiece cavity holder',
      'Motorised Dryco suction with silencer, auto-drain and auto-flush',
      'Woodpecker Non-Optic scaler unit with 5 scaling tips and control switch',
      'X-ray viewer (OPG viewer optional) and multi-functional foot control',
      'Doctor operated dental stool and SS instrument tray',
    ],
    specifications: [
      { label: 'Operation Type', value: 'Electrically operated, 6 programmes' },
      { label: 'Programmes', value: '1-3 erasable, Zero, Gargle, SH-Supine' },
      { label: 'Delivery System', value: 'Modular trolley with hanging cord' },
      { label: 'Light', value: 'LED, 39,000 lux, 3 yellow + 3 white, adjustable lux & kelvin' },
      { label: 'Spittoon', value: 'Ceramic bowl or thick glass bowl' },
      { label: 'Scaler', value: 'Woodpecker Non-Optic scaler, 5 tips, with control switch' },
      { label: 'X-Ray Viewer', value: 'Included (OPG viewer optional)' },
      ...commonChairSpecs,
    ],
  },
  {
    slug: 'beta',
    name: 'Beta',
    tagline: 'Where Precision Meets Patient Comfort',
    kind: 'chair',
    stock: 2,
    lowStockThreshold: 1,
    reorderQuantity: 2,
    category: 'Dental Chairs',
    series: 'Beta Series',
    brand: 'Care Dent',
    sortOrder: 4,
    heroImage: '/products/beta.jpg',
    images: ['/products/beta.jpg'],
    description:
      'A four-programme chair with a non-touch sensor LED light and porcelain spittoon top - a dependable, lower-cost unit for growing practices and second operatories.',
    keyDifferentiators: [
      'Electrically operated with 4 programmes and chair-mounted side attachments',
      '4 LED light with non-touch sensor on/off control and intensity control',
      'Porcelain spittoon top or thick glass bowl',
      'Modular trolley fitted with hanging cord',
      'Motorised Dryco suction with silencer, auto-drain and auto-flush',
      'Woodpecker Non-Optic scaler unit with 5 scaling tips and control switch',
      'X-ray viewer and multi-functional foot control',
      'Doctor operated dental stool and SS instrument tray',
    ],
    specifications: [
      { label: 'Operation Type', value: 'Electrically operated, 4 programmes' },
      { label: 'Light', value: '4 LED with non-touch sensor and intensity control' },
      { label: 'Spittoon', value: 'Porcelain top or thick glass bowl' },
      { label: 'Delivery System', value: 'Modular trolley with hanging cord' },
      { label: 'Scaler', value: 'Woodpecker Non-Optic scaler, 5 tips, with control switch' },
      { label: 'X-Ray Viewer', value: 'Included' },
      ...commonChairSpecs,
    ],
  },
  {
    slug: 'alpha',
    name: 'Alpha',
    tagline: 'Perfect Alignment. Total Comfort',
    kind: 'chair',
    stock: 2,
    lowStockThreshold: 1,
    reorderQuantity: 2,
    category: 'Dental Chairs',
    series: 'Alpha Series',
    brand: 'Care Dent',
    sortOrder: 5,
    heroImage: '/products/alpha.jpg',
    images: ['/products/alpha.jpg'],
    description:
      'The essentials, done properly. Zero-programme operation via hand and foot control, non-touch sensor LED light, and the same Dryco suction and Woodpecker scaler found across the range.',
    keyDifferentiators: [
      'Electrically operated with ZERO programme, operated by hand control and foot control',
      'LED light with non-touch sensor and switch on/off control, plus intensity control',
      'Porcelain spittoon top or thick glass bowl',
      'Modular trolley fitted with hanging cord',
      'Motorised Dryco suction with silencer, auto-drain and auto-flush',
      'Woodpecker Non-Optic scaler unit with 5 scaling tips and control switch',
      'X-ray viewer and multi-functional foot control',
      'Doctor operated dental stool and SS instrument tray',
    ],
    specifications: [
      { label: 'Operation Type', value: 'Electrically operated, ZERO programme (hand + foot control)' },
      { label: 'Light', value: 'LED with non-touch sensor, switch and intensity control' },
      { label: 'Spittoon', value: 'Porcelain top or thick glass bowl' },
      { label: 'Delivery System', value: 'Modular trolley with hanging cord' },
      { label: 'Scaler', value: 'Woodpecker Non-Optic scaler, 5 tips, with control switch' },
      { label: 'X-Ray Viewer', value: 'Included' },
      ...commonChairSpecs,
    ],
  },

  /* ------------------------------ other equipment ------------------------------ */
  {
    slug: 'portable-x-ray-units',
    name: 'Portable X-Ray Units',
    tagline: 'Point-of-care radiography',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Radiology',
    brand: 'Woodpecker',
    sortOrder: 10,
    heroImage: '/products/x-ray-units.jpg',
    images: ['/products/x-ray-units.jpg'],
    description:
      'High-frequency portable and wall-mounted dental X-ray machines with low radiation leakage, fast exposure times and a lightweight handheld body for chairside imaging.',
    keyDifferentiators: [
      'High-frequency generator with short exposure times',
      'Low radiation leakage, operator-safe shielding',
      'Handheld portable and wall-mounted variants',
      'Compatible with digital sensors and phosphor plates',
    ],
    specifications: [
      { label: 'Type', value: 'Handheld portable / wall-mounted' },
      { label: 'Generator', value: 'High frequency DC' },
      { label: 'Sensor Support', value: 'Digital sensor and phosphor plate compatible' },
    ],
  },
  {
    slug: 'autoclaves-sterilization',
    name: 'Autoclaves & Sterilization',
    tagline: 'Class B vacuum sterilization',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Sterilization',
    brand: 'Woodpecker',
    sortOrder: 11,
    heroImage: '/products/autoclaves.jpg',
    images: ['/products/autoclaves.jpg', '/products/uv-cabinet.jpg'],
    description:
      'Class B vacuum autoclaves with fractionated pre-vacuum cycles for complete infection control, plus UV sterilization cabinets for instrument storage.',
    keyDifferentiators: [
      'Class B fractionated pre-vacuum cycle',
      'Handles hollow, porous and wrapped loads',
      'Rapid cycle times with automatic drying',
      'UV storage cabinets available',
    ],
    specifications: [
      { label: 'Class', value: 'Class B vacuum' },
      { label: 'Capacity', value: '12L / 18L / 23L options' },
      { label: 'Cycles', value: 'Wrapped, unwrapped, hollow, prion, B&D test' },
    ],
  },
  {
    slug: 'led-curing-lights',
    name: 'LED Curing Lights',
    tagline: 'Broad-spectrum cordless curing',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Restorative',
    brand: 'Woodpecker',
    sortOrder: 12,
    heroImage: '/products/curing-light.jpg',
    images: ['/products/curing-light.jpg'],
    description:
      'Broad-spectrum, high-power cordless LED curing lamps with a fast one-second mode, covering camphorquinone and alternative photoinitiators.',
    keyDifferentiators: [
      'Broad-spectrum output for all common photoinitiators',
      'One-second fast cure mode',
      'Cordless with high-capacity lithium battery',
      'Built-in light meter and orthodontic mode',
    ],
    specifications: [
      { label: 'Wavelength', value: 'Broad spectrum 385-515 nm' },
      { label: 'Modes', value: 'Fast / Ramp / Pulse / Ortho' },
      { label: 'Power', value: 'Cordless lithium battery' },
    ],
  },
  {
    slug: 'ultrasonic-scalers',
    name: 'Ultrasonic Scalers',
    tagline: 'Optic and non-optic piezo scaling',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Prophylaxis',
    brand: 'Woodpecker',
    sortOrder: 13,
    heroImage: '/products/scaler.jpg',
    images: ['/products/scaler.jpg'],
    description:
      'Optic and non-optic piezo ultrasonic scalers with detachable, fully autoclavable handpieces and a five-tip scaling set - the same units fitted to our Gamma chairs.',
    keyDifferentiators: [
      'Piezo-electric scaling with automatic frequency tracking',
      'Detachable, fully autoclavable handpiece',
      '5 specialised scaling tips included',
      'Optic (LED) and non-optic variants',
    ],
    specifications: [
      { label: 'Type', value: 'Piezo ultrasonic' },
      { label: 'Variants', value: 'Optic (LED) / Non-optic' },
      { label: 'Tips', value: '5-tip scaling set' },
      { label: 'Handpiece', value: 'Detachable, autoclavable' },
    ],
  },
  {
    slug: 'oil-free-air-compressors',
    name: 'Oil-Free Air Compressors',
    tagline: 'Medical grade, ultra quiet',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Utility',
    brand: 'Care Dent Premium',
    sortOrder: 14,
    heroImage: '/products/compressor.jpg',
    images: ['/products/compressor.jpg'],
    description:
      'Ultra-quiet medical grade oil-free air compressors with internally coated tanks, sized for one to four chair operatories.',
    keyDifferentiators: [
      'Oil-free medical grade air - no oil contamination',
      'Internally coated tank resists corrosion',
      'Ultra-quiet operation suitable for surgery-adjacent placement',
      'Single and twin head configurations',
    ],
    specifications: [
      { label: 'Type', value: 'Oil-free, medical grade' },
      { label: 'Configurations', value: 'Single head / twin head' },
      { label: 'Chairs Supported', value: '1 to 4 depending on model' },
    ],
  },
  {
    slug: 'dental-micromotors',
    name: 'Dental Micromotors',
    tagline: 'High-torque brushless control',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Endodontics',
    brand: 'Saeyang Marathon',
    sortOrder: 15,
    heroImage: '/products/micromotor.jpg',
    images: ['/products/micromotor.jpg', '/products/handpiece.jpg'],
    description:
      'High-torque brushless Saeyang Marathon micromotors for prosthetic, laboratory and surgical work, with forward/reverse control and variable speed.',
    keyDifferentiators: [
      'Brushless motor - high torque, low heat, long service life',
      'Variable speed with forward and reverse',
      'Suitable for prosthetic, lab and surgical applications',
      'Foot control option available',
    ],
    specifications: [
      { label: 'Motor', value: 'Brushless' },
      { label: 'Speed', value: 'Variable, forward / reverse' },
      { label: 'Applications', value: 'Prosthetic, laboratory, surgical' },
    ],
  },
  {
    slug: 'ergonomic-dental-stools',
    name: 'Ergonomic Dental Stools',
    tagline: 'Doctor and assistant seating',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Furniture',
    brand: 'Care Dent',
    sortOrder: 16,
    heroImage: '/products/stools.jpg',
    images: ['/products/stools.jpg'],
    description:
      'Doctor and assistant stools with 3D adjustable armrests, lumbar back support and smooth-rolling castors - supplied as standard with every Care Dent chair.',
    keyDifferentiators: [
      '3D adjustable armrests',
      'Lumbar back support',
      'Gas-lift height adjustment',
      'Smooth-rolling castor base',
    ],
    specifications: [
      { label: 'Variants', value: 'Doctor stool / assistant stool' },
      { label: 'Adjustment', value: 'Gas lift, 3D armrests, tilt' },
      { label: 'Upholstery', value: 'Wipe-clean, disinfectant safe' },
    ],
  },
  {
    slug: 'handpieces-accessories',
    name: 'Handpieces & Accessories',
    tagline: 'Airotors, contra-angles and consumables',
    kind: 'equipment',
    stock: 6,
    lowStockThreshold: 2,
    reorderQuantity: 5,
    category: 'Accessories',
    brand: 'Saeyang / Woodpecker',
    sortOrder: 17,
    heroImage: '/products/handpiece.jpg',
    images: ['/products/handpiece.jpg'],
    description:
      'High-speed LED airotors, contra-angle handpieces, apex locators, endo motors, maintenance oils and the full range of spares we stock for same-week replacement.',
    keyDifferentiators: [
      'High-speed LED airotors with push-button chuck',
      'Contra-angle and straight handpieces',
      'Apex locators and endo motors',
      'Maintenance oils, lubricants and spares held in stock',
    ],
    specifications: [
      { label: 'Coupling', value: 'Standard 4-hole / 2-hole' },
      { label: 'Chuck', value: 'Push button' },
      { label: 'Spares', value: 'Held in stock for same-week replacement' },
    ],
  },
];

export const SERVICES = [
  {
    key: 'installation',
    title: 'Professional Installation',
    iconName: 'Wrench',
    sortOrder: 1,
    description:
      'Precision installation of dental chairs, utility pipelines, compressors and digital X-ray sensors by certified engineers, including commissioning and handover training.',
  },
  {
    key: 'maintenance',
    title: 'Routine Maintenance',
    iconName: 'ShieldCheck',
    sortOrder: 2,
    description:
      'Scheduled preventive maintenance covering tubing, valves, motor lubrication, suction flushes and light calibration - keeping small faults from becoming downtime.',
  },
  {
    key: 'amc',
    title: 'Annual Maintenance Contract (AMC)',
    iconName: 'Calendar',
    sortOrder: 3,
    description:
      'All-inclusive yearly contracts: regular scheduled visits, free emergency call-outs, priority response and discounted spares. Priced per chair, with multi-chair rates.',
  },
  {
    key: 'repair',
    title: 'Breakdown & Fault Repair',
    iconName: 'Activity',
    sortOrder: 4,
    description:
      'Rapid-response repair for electrical, pneumatic, hydraulic and electronic chair faults, backed by a stocked spares inventory so most repairs finish in one visit.',
  },
  {
    key: 'support',
    title: 'Technical Remote Support',
    iconName: 'PhoneCall',
    sortOrder: 5,
    description:
      'Direct phone access to Sivakumar sir and our technicians for quick diagnosis, operational guidance and fixes you can carry out yourself before booking a visit.',
  },
  {
    key: 'inspection',
    title: 'Pre-Purchase & Safety Inspection',
    iconName: 'ClipboardCheck',
    sortOrder: 6,
    description:
      'Multi-point clinical audit covering electrical safety, radiation safety and structural integrity - essential before buying a used unit or renewing a clinic licence.',
  },
];
