import path from 'node:path';
import fs from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { S3Client, GetObjectCommand, DeleteObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';
import { env, isProd } from './env.js';

/**
 * Where uploaded files actually live.
 *
 * Everything used to go to ./uploads on the container filesystem, which most
 * hosts - Render, Railway, Fly, a Vercel function, any container that is
 * rebuilt rather than restarted - wipe on every deploy. Product photographs
 * and the floor plans clinics attach to a site assessment were being lost on a
 * schedule nobody had chosen.
 *
 * Two drivers behind one interface:
 *
 *   s3    Any S3-compatible bucket - AWS S3, Cloudflare R2, Backblaze B2,
 *         DigitalOcean Spaces. Set S3_BUCKET and credentials to select it.
 *   disk  ./uploads, as before. The default, because it needs no account and
 *         keeps `npm run dev` working out of the box.
 *
 * Objects are read back through the API rather than linked to directly, so the
 * bucket stays private and the URLs already stored on Product, Document and
 * ServiceTicket records keep working unchanged. That costs the app the
 * bandwidth; at this traffic that is a fair trade for not having to make a
 * customer's floor plan public to serve it.
 */

const UPLOAD_ROOT = path.resolve(process.cwd(), 'uploads');

const s3Configured = Boolean(env.s3.bucket && env.s3.accessKeyId && env.s3.secretAccessKey);

/**
 * Disk in production is a warning, not an error. Refusing to boot would take
 * the whole API down over a problem that only touches attachments, and the
 * site sells equipment through forms that do not need one.
 */
if (!s3Configured && isProd) {
  console.warn(
    '\n[storage] S3 is not configured - uploads are going to the container filesystem.\n' +
    '[storage] Most hosts wipe that on every deploy. Set S3_BUCKET, S3_ACCESS_KEY_ID\n' +
    '[storage] and S3_SECRET_ACCESS_KEY to keep uploaded files.\n'
  );
}

const client = s3Configured
  ? new S3Client({
      region: env.s3.region,
      // R2, B2 and Spaces are S3-compatible but not on AWS's hostnames.
      ...(env.s3.endpoint ? { endpoint: env.s3.endpoint, forcePathStyle: true } : {}),
      credentials: {
        accessKeyId: env.s3.accessKeyId,
        secretAccessKey: env.s3.secretAccessKey,
      },
    })
  : null;

/**
 * A key is "images/chair-a1b2c3.jpg" - the bucket segment and the filename,
 * both generated by us. Reject anything that could climb out of the prefix:
 * the key reaches here from a URL path on the read side.
 */
const isSafeKey = (key) =>
  typeof key === 'string' &&
  /^(images|documents)\/[A-Za-z0-9._-]+$/.test(key) &&
  !key.includes('..');

const diskPathFor = (key) => path.join(UPLOAD_ROOT, key);

/* ------------------------------- writing ------------------------------- */

/**
 * Streams one upload into the store.
 *
 * The stream's length is not known ahead of time - multer hands over a live
 * request stream - so the S3 path goes through lib-storage's Upload, which
 * negotiates a multipart transfer instead of demanding a Content-Length.
 */
export async function putObject(key, stream, contentType) {
  if (!isSafeKey(key)) throw new Error(`Refusing to write unsafe key: ${key}`);

  if (client) {
    await new Upload({
      client,
      params: { Bucket: env.s3.bucket, Key: key, Body: stream, ContentType: contentType },
    }).done();
    return;
  }

  const target = diskPathFor(key);
  await fs.promises.mkdir(path.dirname(target), { recursive: true });
  await pipeline(stream, fs.createWriteStream(target));
}

/* ------------------------------- reading ------------------------------- */

/**
 * Opens an object for streaming to the client, or null when there is no such
 * object. Callers get the metadata they need for the response headers.
 */
export async function getObject(key) {
  if (!isSafeKey(key)) return null;

  if (client) {
    try {
      const out = await client.send(new GetObjectCommand({ Bucket: env.s3.bucket, Key: key }));
      return {
        stream: out.Body,
        contentType: out.ContentType,
        contentLength: out.ContentLength,
        lastModified: out.LastModified,
        etag: out.ETag,
      };
    } catch (err) {
      if (err.name === 'NoSuchKey' || err.$metadata?.httpStatusCode === 404) return null;
      throw err;
    }
  }

  const target = diskPathFor(key);
  try {
    const stat = await fs.promises.stat(target);
    if (!stat.isFile()) return null;
    return {
      stream: fs.createReadStream(target),
      contentLength: stat.size,
      lastModified: stat.mtime,
    };
  } catch {
    return null;
  }
}

/* ------------------------------ deleting ------------------------------- */

/** Never throws: a file we failed to delete must not fail the request. */
export async function deleteObject(key) {
  if (!isSafeKey(key)) return;
  try {
    if (client) {
      await client.send(new DeleteObjectCommand({ Bucket: env.s3.bucket, Key: key }));
    } else {
      await fs.promises.unlink(diskPathFor(key));
    }
  } catch {
    /* already gone, or the store is unreachable - neither is worth an error */
  }
}

/** Whether the store holds this key. Used by the seed and by tooling. */
export async function objectExists(key) {
  if (!isSafeKey(key)) return false;
  try {
    if (client) {
      await client.send(new HeadObjectCommand({ Bucket: env.s3.bucket, Key: key }));
      return true;
    }
    return (await fs.promises.stat(diskPathFor(key))).isFile();
  } catch {
    return false;
  }
}

export const storageDriver = client ? 's3' : 'disk';
export { UPLOAD_ROOT, isSafeKey };
